"use client";

import Link from "next/link";
import { ImagePlus, Link2, MonitorUp, ToggleLeft } from "lucide-react";
import { ChangeEvent, FormEvent, useEffect, useState } from "react";

type ManagedAd = { id: string; title: string; placement: string; link: string; image: string; active: boolean };

const placementNames: Record<string, string> = { HOME_SLIDER: "สไลด์หน้าแรก", HOME_MID: "กรอบกลางหน้าแรก", HOME_SIDEBAR: "กรอบด้านข้าง", HOME_BOTTOM: "กรอบท้ายหน้าแรก" };

export default function AdminAdsPage() {
  const [image, setImage] = useState("");
  const [ads, setAds] = useState<ManagedAd[]>([]);
  const [message, setMessage] = useState("");
  useEffect(() => { fetch("/api/admin/ads").then(async (response) => response.ok ? response.json() : []).then((items) => setAds(items.map((item: { id: string; title: string; placement: string; targetUrl: string; imageUrl: string; active: boolean }) => ({ id: item.id, title: item.title, placement: item.placement, link: item.targetUrl, image: item.imageUrl, active: item.active })))).catch(() => setMessage("กรุณาเข้าสู่ระบบผู้ดูแลก่อนจัดการโฆษณา")); }, []);
  function chooseImage(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (file) setImage(URL.createObjectURL(file)); }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); data.set("targetUrl", String(data.get("link") ?? "")); data.delete("link"); const response = await fetch("/api/admin/ads", { method: "POST", body: data }); const result = await response.json(); if (!response.ok) { setMessage(result.error ?? "ไม่สามารถบันทึกโฆษณาได้"); return; } setAds((items) => [{ id: result.id, title: result.title, placement: result.placement, link: result.targetUrl, image: result.imageUrl, active: result.active }, ...items]); setMessage("บันทึกและเผยแพร่โฆษณาแล้ว"); event.currentTarget.reset(); setImage(""); }
  async function toggle(ad: ManagedAd) { const response = await fetch("/api/admin/ads", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: ad.id, active: !ad.active }) }); if (response.ok) setAds((items) => items.map((item) => item.id === ad.id ? { ...item, active: !item.active } : item)); else setMessage("ไม่สามารถเปลี่ยนสถานะโฆษณาได้"); }
  return <main className="admin-ads"><header className="admin-header"><div><div className="simple-kicker">ADMIN CONSOLE</div><h1>จัดการโฆษณา</h1></div><Link href="/" className="back-link">ดูหน้าเว็บไซต์</Link></header><div className="admin-grid"><section className="admin-form-panel"><div className="panel-head"><strong>เพิ่มโฆษณาใหม่</strong><small>รูปภาพ + ลิงก์ปลายทาง</small></div><form onSubmit={submit} className="admin-form"><label>ชื่อโฆษณา<input name="title" required placeholder="เช่น โปรสมาชิก Silver" /></label><label>ตำแหน่งแสดงผล<select name="placement">{Object.entries(placementNames).map(([value, name]) => <option key={value} value={value}>{name}</option>)}</select></label><label>ลิงก์เมื่อคลิก<input name="link" required placeholder="https://... หรือ /plans" /></label><label>รูปภาพโฆษณา<input name="image" required type="file" accept="image/jpeg,image/png,image/webp" onChange={chooseImage} /><span className="upload-hint"><ImagePlus size={18} />รองรับ JPG, PNG, WEBP</span></label>{image && <img className="admin-preview" src={image} alt="ตัวอย่างโฆษณา" />}<button className="payment-submit"><MonitorUp size={17} />เพิ่มเข้ารายการโฆษณา</button>{message && <p className="success-note">{message}</p>}</form></section><section className="admin-list-panel"><div className="panel-head"><strong>รายการโฆษณา</strong><small>{ads.length} รายการ</small></div>{ads.length === 0 ? <div className="admin-empty"><ImagePlus size={26} /><p>ยังไม่มีโฆษณาที่เผยแพร่</p></div> : <div className="admin-ad-list">{ads.map((ad) => <article className="admin-ad-row" key={ad.id}><img src={ad.image} alt="" /><div><b>{ad.title}</b><span>{placementNames[ad.placement]}</span><small><Link2 size={11} />{ad.link}</small></div><button className={ad.active ? "ad-active" : "ad-inactive"} onClick={() => toggle(ad)}><ToggleLeft size={15} />{ad.active ? "เปิด" : "ปิด"}</button></article>)}</div>}</section></div></main>;
}
