"use client";

import Link from "next/link";
import { Camera, Check, KeyRound, Medal, MessageCircle, Save, ShieldCheck, UserRound } from "lucide-react";
import { useEffect, useState } from "react";
import type { MemberIdentity } from "../../components/member-menu";

export default function ProfilePage() {
  const [member, setMember] = useState<MemberIdentity | null>(null);
  const [avatar, setAvatar] = useState("");
  const [saved, setSaved] = useState(false);
  useEffect(() => { fetch("/api/auth/session").then((response) => response.json()).then((data) => { setMember(data.member ?? null); setAvatar(localStorage.getItem("betpay_avatar") ?? data.member?.avatarUrl ?? ""); }).catch(() => undefined); }, []);
  function handleAvatar(event: React.ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { const value = String(reader.result); setAvatar(value); localStorage.setItem("betpay_avatar", value); }; reader.readAsDataURL(file); }
  if (!member) return <main className="simple-shell"><div className="simple-page"><div className="simple-kicker">MEMBERS AREA</div><h1>กรุณาเข้าสู่ระบบ</h1><Link className="payment-submit" href="/login">เข้าสู่ระบบสมาชิก</Link></div></main>;
  const medal = member.role === "ADMIN" || member.tier === "GOLD" ? "GOLD" : member.tier === "SILVER" ? "SILVER" : "MEMBER";
  return <main className="simple-shell"><header className="simple-header"><Link href="/" className="back-link">กลับหน้าทีเด็ด</Link><span className="simple-brand">Bet<span>Pay</span></span><Link href="/plans" className="muted-link">แพ็กเกจสมาชิก</Link></header><div className="profile-page"><div className="simple-kicker">MEMBER PROFILE</div><h1>โปรไฟล์ของฉัน</h1><p className="simple-lead">จัดการข้อมูลสมาชิก รูป Avatar และสิทธิ์การใช้งานของคุณ</p><div className="profile-grid"><section className="profile-card profile-identity"><div className={`profile-avatar medal-${medal.toLowerCase()}`}>{avatar ? <img src={avatar} alt="Avatar" /> : member.displayName.charAt(0)}</div><label className="avatar-upload"><Camera size={15} />เปลี่ยนรูป Avatar<input type="file" accept="image/*" onChange={handleAvatar} /></label><h2>{member.displayName}</h2><p>{member.email}</p><span className={`profile-medal medal-text-${medal.toLowerCase()}`}><Medal size={15} />MEDAL {medal}</span><div className="profile-links"><Link href="/chat"><MessageCircle size={16} />ช่อง Chat</Link><Link href="/forum"><ShieldCheck size={16} />เว็บบอร์ด</Link></div></section><section className="profile-card"><div className="profile-section-head"><div><span className="simple-kicker">ACCOUNT</span><h2>รายละเอียดบัญชี</h2></div><UserRound size={20} /></div><div className="profile-fields"><label>ชื่อเล่น<input defaultValue={member.displayName} /></label><label>อีเมล<input value={member.email} readOnly /></label></div><button className="payment-submit" type="button" onClick={() => { setSaved(true); setTimeout(() => setSaved(false), 2200); }}><Save size={16} />{saved ? "บันทึกแล้ว" : "บันทึกข้อมูล"}</button><div className="profile-password"><div><KeyRound size={18} /><strong>เปลี่ยนรหัสผ่าน</strong></div><p>เปลี่ยนรหัสผ่านเพื่อรักษาความปลอดภัยของบัญชี</p><button className="profile-outline" type="button">ตั้งรหัสผ่านใหม่</button></div></section></div><section className="profile-card profile-perks"><div><h2>สิทธิ์ของคุณ</h2><p>ระดับปัจจุบัน: <strong>{member.tier === "GOLD" ? "Gold" : member.tier === "SILVER" ? "Silver" : "Member"}</strong></p></div><div className="perk-list"><span><Check size={15} />ดูผลการแข่งขัน</span><span className={member.tier === "MEMBER" ? "locked" : ""}><Check size={15} />Chat สมาชิก</span><span className={member.tier !== "GOLD" ? "locked" : ""}><Check size={15} />แจ้งเตือนและ Webboard</span></div></section></div></main>;
}
